name: deploy
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: 6.0.x
      - name: Restore dependiences
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Publish
        run: dotnet publish -c Release -o ${{ env.DOTNET_ROOT }}/api
      - name: upload artifact
        uses: actions/upload-artifact@v2.3.1
        with:
         name: api-artifact
         path: ${{ env.DOTNET_ROOT }}/api  
  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'DEV'
      url: ${{ steps.deploy-to-azure.outputs.webapp-url }}
    steps:
     - name: Download a Build Artifact
       uses: actions/download-artifact@v2.1.0
       with:
        name: api-artifact
     - name: Azure WebApp deploy
       id: deploy-to-azure
       uses: Azure/webapps-deploy@v2
       with:
        app-name: 'advertisementapp'
        publish-profile: ${{ secrets.PUBLISH_PROFILE_DEV }}
        
